web:
   image: wordpress
   links:
    - db:mysql
   ports:
    - '8001:80'
   working_dir: '/var/www/html'
   volumes:
    - "./html:/var/www/html"
                                                             
db:
   image: mysql
   environment:
    MYSQL_ROOT_PASSWORD: 'password'
