version: '2'

services:
                                           
 db:
   image: mysql
   environment:
    MYSQL_ROOT_PASSWORD: 'password'


 myadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - '8002:80'

 web:
   image: wordpress
   ports:
    - '80:80'
   working_dir: '/var/www/html'
   volumes:
    - "./html:/var/www/html"
   links:
    - "db:mysql"
   environment:
    WORDPRESS_DB_NAME: 'wordpress'
    WORDPRESS_DB_PASSWORD  : 'password'
    WORDPRESS_DB_USER : 'root'
